export const DashboardActions = {
  UPDATE_USER_STATE: 'UPDATE_USER_STATE',
  GET_USERS_LIST: 'GET_USERS_LIST',
  GET_USERS_LIST_SUCCESS: 'GET_USERS_LIST_SUCCESS',
  GET_USERS_LIST_FAILURE: 'GET_USERS_LIST_FAILURE',
};
